### ISSUE TITLE
Feature Request: STA Test Constructors

### ISSUE THREAD

**Issue by TheMinefighter** [AArnott/Xunit.StaFact#12]
I have case where I have to initialize my Testclass with some UI (WPF) code, requiring STA Execution. Therefore it would be great if I was able to mark the constructor / test initalizer as `[StaInitalizer]` (or whatever you want to call it.

**Comment by AArnott** [comment]
Whenever you use `[StaFact]`, the test class constructor runs on the same STA as the test method. See the linked commit above for a test to demonstrate this.
