### ISSUE TITLE
Support for .Net 4.7?

### ISSUE THREAD

**Issue by dksphillips** [AArnott/Xunit.StaFact#13]
I would like to use this package with .Net 4.7. Is there any chance to that it can be updated to support the latest verison of .Net Standard?

**Comment by AArnott** [comment]
This project already supports net452, netstandard1.1, and later. It should already work on .NET Framework 4.7. If you're seeing issues with it, can you please elaborate on that?

https://github.com/AArnott/Xunit.StaFact/blob/6521a0f44aabc21f506035a0f613ad8d5ca8b298/src/Xunit.StaFact/Xunit.StaFact.csproj#L3
