### ISSUE TITLE
Any chance of getting UITheory/StaTheory?

### ISSUE THREAD

**Issue by AdamYoblick** [AArnott/Xunit.StaFact#17]
Just wondering if there's any plan to add theory attributes for the other types of facts. Right now, the only theory is WpfTheory.

Thanks :)

**Comment by AArnott** [comment]
I vaguely remember at one point I tried but there was an xunit deficiency that made the other theories hard to implement. That's probably resolved by now. But yours is the first request for it. :)

I'm happy to add them. Even happier to take a PR that adds them (and tests). It'll probably happen faster if I just get to review a PR. 😄

**Comment by apobekiaris** [comment]
2nd request here, what I am really interested is Autofixture support, but I guess the Theory support should be enough for it.

**Comment by AArnott** [comment]
What is autofixture?

**Comment by AArnott** [comment]
Ah, that should work so long as you have a theory attribute.

**Comment by apobekiaris** [comment]
i tried to build but you use .NETCore 3. I cannot discover any download url for that

**Comment by AArnott** [comment]
Ya, I added that because for .NET Core 3.0 development, they're using this library.
Try checkout out the `pre-netcore3` branch (which I just pushed). You should be able to build that, and any changes you make could then be merged into `master`. To try avoid any tempting build authoring or dependency updates though, to help avoid merge conflicts with master.

**Comment by apobekiaris** [comment]
I sent a PR where my tests pass locally. I worked in the pre-core branch and then merge to the master so I probably miss something and the builds fails. Maybe you can have a look? I already use the new WinFormsTheoryAttribute on my side in my tests and works fine. 

Many thanks for the straightforward project-guide you have here.

**Comment by AArnott** [comment]
Thanks. I've completed your PR, @apobekiaris. I'm also about to complete #10 which adds `StaTheoryAttribute`.

Last up will be `UITheoryAttribute`.
