### ISSUE TITLE
[StaFact] tests not found when used with netcoreapp2.2

### ISSUE THREAD

**Issue by gavinbeatty** [AArnott/Xunit.StaFact#26]
If I create a simple test project `dotnet new xunit` targeting netcoreapp2.2, and `dotnet add sample.csproj package Xunit.StaFact --version 0.3.18`, change example `[Fact]` to `[StaFact]`, and no tests are found when running `dotnet test`.

**Comment by gavinbeatty** [comment]
Confirmed no tests found for netcoreapp1.0 - 2.2 inclusive.

**Comment by AArnott** [comment]
I'm sure I've had this working, but maybe it regressed. Or maybe the dotnet CLI broke it. Have you tried running tests within VS for this same project?

**Comment by gavinbeatty** [comment]
`UIFact` works.

Given my tests are not GUI related, I’d expect to be able to use `StaFact`.

**Comment by gavinbeatty** [comment]
`StaFactDiscoverer` only exists in Sdk.Desktop/, which is excluded for netcoreapp < 3.0 and netstandard. `UIFactDiscoverer` is in Sdk/.

**Comment by AArnott** [comment]
Ah, nice catch. I suspect we can't expand that support (probably some barrier got in the way), but we should look at hiding the attribute where we can't support it.

**Comment by gavinbeatty** [comment]
I’m totally ignorant about apartments, but it’s a little odd to have to use UIFact in tests for a library with no UI elements. What’s the difference between Sta and UI variants?

**Comment by AArnott** [comment]
`[STAFact]` just _starts_ your test on an STA thread. That's it. It doesn't keep it there across yielding awaits either. It's analogous to `[STAThread]` on your `Main` method in a C# console app.

`[UIFact]` arranges a `SynchronizationContext` that keeps your test on the same thread across awaits. So you have a concept of a 'main thread', allowing testing of code that cares that it is only used from one thread happy (e.g. WPF).

Does that help?

**Comment by gavinbeatty** [comment]
Yes, definitely. I’m using StaFact to force xunit 2 to act like xunit 1 re: threads, as part of porting a very old project to .NET Core.

From a functionality standpoint, UIFact seems ideal for me, if a little confusingly named. I can’t think of a good alternative name except MainThreadFact? A bit long perhaps.

**Comment by AArnott** [comment]
> Final thing is just to echo your own suggestion that StaFact should not be available if the discoverer isn’t.

The only thing IIRC with that is that if the test library (or one it references) targets .netstandard, then we want the attribute to be present so they can apply it, even though we do not yet know whether the underlying runtime (i.e. the test project itself) will run on a platform that supports it. So I'm not sure how to bridge those two ideals.

**Comment by gavinbeatty** [comment]
If it’s unimplementable on netcoreapp, then is it possible to make the test discoverable but always fail? Better UX.

**Comment by gavinbeatty** [comment]
What version on nuget contains this? I don’t see version match in tags vs. nuget releases.

**Comment by AArnott** [comment]
> I don’t see version match in tags vs. nuget releases.

I wonder what you saw there. I checked the tags and nuget releases and they appear to line up. I try to push a tag every time I push a package.

> What version on nuget contains this?

None of them. I haven't released since making this fix. Just an oversight. I'll do that now.

**Comment by AArnott** [comment]
It will appear as 1.0.3-beta on nuget.org
