### ISSUE TITLE
Unmanaged memory and handles leak

### ISSUE THREAD

**Issue by Xarlot** [AArnott/Xunit.StaFact#3]
Hi,
I have detected a huge memory and handles leak during my porting our legacy tests from old version of nunit to xunit. Test runner has been crashed after ~1000 test suits with out of memory exception, ~2 gb unmanaged memory was taken, managed heap was ~250 mb. After investigating this issue i have found a problem, you are creating a new thread for each test suite. I have fixed it in my fork using thread pool. https://github.com/Xarlot/Xunit.StaFact/commit/fb2c15da79c088219f5592ac6269c855a7bf8529
However, it added an additional external reference, so i prefer to write an issue than create a pull request.

**Comment by AArnott** [comment]
Creating a new thread isn't a leak. These threads get destroyed at the end of each test. Why do you say it leaked?
