### ISSUE TITLE
Support for OleInitialize

### ISSUE THREAD

**Issue by weltkante** [AArnott/Xunit.StaFact#31]
OLE has an explicit [`OleInitialize`](https://docs.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-oleinitialize) native call which is required in addition to STA for OLE based functions and COM classes to work properly. This came up in the discussion of dotnet/winforms#1999 and recent list of unstable tests which all target OLE interfaces.

A [bunch of classes](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Application.cs,882d37f86d6a1b27,references) like [`ComponentManager`](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Application.ThreadContext.cs,173), [`Clipboard`](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Clipboard.cs,91), [`AxHost`](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/AxHost.cs,261) etc. do call `Application.OleRequired` to setup/verify STA. But when testing the internals of WinForms you often don't go through those public APIs and test the OLE APIs more directly, so you are missing the OleInitialize call and I think this may at least partly responsible for unstable tests:

dotnet/winforms#2002
dotnet/winforms#2003
~~dotnet/winforms#2004~~
~~dotnet/winforms#2005~~

There has been no analysis done yet to verify whether calling `Application.OleRequired` will fix above tests, but considering that `WinFormsFactAttribute` is already using a `Windows­Forms­Synchronization­Context` it may be reasonable to also call `Application.OleRequired` on that thread just in case the tests will need OLE.

**Comment by weltkante** [comment]
Sorry, I didn't want to give the impression that its urgent, I'm still working on reproducing the test failures on my own environment.

The two IPicture/IPictureDisp failures seem independent from OleInitialize, I'm still working on reproducing the IFont/IFontDisp failures.

In either case it seems the right thing to do.

**Comment by AArnott** [comment]
Thanks. I'll move forward with it then.
