### ISSUE TITLE
CPU usage in polling message loop

### ISSUE THREAD

**Issue by weltkante** [AArnott/Xunit.StaFact#43]
[PumpTill](https://github.com/AArnott/Xunit.StaFact/blob/68790c28e568e4634da2c226fb1324f0cedd5974/src/Xunit.StaFact/Sdk.Desktop/WinFormsSynchronizationContextAdapter.cs#L30-L34) has a polling message loop that even though its yielding the thread still causes high CPU load. This can be done better, at least in WinForms. An example how to do a CPU friendly modal loop is [here](https://github.com/dotnet/winforms/blob/5b63e3a0e26cd1385e17b023f00fd6d17bd1b8b2/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs#L2405-L2413)

**Comment by AArnott** [comment]
Oh yikes, I might try to deny any memory of having written that code. Yuck.
Anyway, thanks for the tip on what handles I can sleep on to do better there.

**Comment by AArnott** [comment]
I wonder though... those handles are user input centric, which don't apply at all in a unit test. You wouldn't want your unit test to hang just because there was no one there to move the mouse. I'm going to study why I'm in a DoEvents loop at all and see if there's a better option.

**Comment by weltkante** [comment]
This is not waiting on handles, it waits on a 250ms timeout or a message arriving in the message queue

**Comment by weltkante** [comment]
The alternative would probably be pushing an [ApplicationContext](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.applicationcontext?view=netcore-3.1) frame similar to what you do in WPF, and then registering a callback to the task to terminate that frame.
