### ISSUE TITLE
.net 4.5.2 compatibility

### ISSUE THREAD

**Issue by antrv** [AArnott/Xunit.StaFact#50]
Please keep Nuget package compatibility with .net 4.5.2
The latest Nuget 1.0.37 has no .net 4.5.2 support.

**Comment by AArnott** [comment]
Can you elaborate on why this is important to you? Can you stick to the older package version? What prevents you from upgrading your target framework?

**Comment by antrv** [comment]
Thank you. I can stick the older package version actually.

**Comment by AArnott** [comment]
Great. The net452 support was expensive to maintain which is why we cut it out.
