### ISSUE TITLE
InvalidComObjectException on test cleanup when window is shown

### ISSUE THREAD

**Issue by ilengyel** [AArnott/Xunit.StaFact#6]
`InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.`

is thrown when a window is shown in a WpfFact. Example:
    
    [WpfFact]
    public void ShouldShowWindow()
    {
        var window = new Window();
        window.Show();

        Assert.True(window.IsVisible);
    }

The cause and solution is mentioned here: http://stackoverflow.com/questions/17194361/why-closing-window-created-in-a-unit-test-raises-an-invalidcomobjectexception

I made some changes in a fork to get us over the line:  https://github.com/AArnott/Xunit.StaFact/pull/5
Hopefully it can be incorporated, let me know if I need to change any conventions in the pull request.

Regards,

**Comment by ilengyel** [comment]
FYI this is the full xunit.console output for the above test
```
D:\DEV\AE\GIT\Investigations\Xunit.StaFact\packages>xunit.runner.console.2.1.0\tools\xunit.console.exe ..\src\Xunit.StaFact.Tests\bin\Debug\Xunit.StaFact.Tests.dll -method WpfFactTests.ShouldShowWindow -verbose
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Xunit.StaFact.Tests
  Discovered:  Xunit.StaFact.Tests
  Starting:    Xunit.StaFact.Tests
    WpfFactTests.ShouldShowWindow
  Finished:    Xunit.StaFact.Tests
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.Windows.Input.TextServicesContext.StopTransitoryExtension()
   at System.Windows.Input.TextServicesContext.Uninitialize(Boolean appDomainShutdown)
   at MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
```

**Comment by bradphelan** [comment]
I just got the same problem. The issue has a solution.

http://stackoverflow.com/questions/17194361/why-closing-window-created-in-a-unit-test-raises-an-invalidcomobjectexception

**Comment by ilengyel** [comment]
#5 is now incorporated in the 0.1.44-beta version just published. This issue can be marked as fixed. Thanks @AArnott

**Comment by AArnott** [comment]
Thank *you*, @ilengyel.
